### ISSUE TITLE
type in async action

### ISSUE THREAD

**Issue by rplotkin** [xdave/typescript-fsa-redux-thunk#10]
error TS2345: Argument of type '(dispatch: Dispatch<{}>, getState: () => {}, e: any) => Action<Success<{ foo: string; }, { bar: n...' is not assignable to parameter of type 'Action'.
  Property 'type' is missing in type '(dispatch: Dispatch<{}>, getState: () => {}, e: any) => Action<Success<{ foo: string; }, { bar: n...'.

Using the default example for async, I get the error above when I try to use the Worker as an action. It should, I think, have a type property in the resulting transformation to an Action, so that it is, indeed, an acceptable action type. Unless there's another way?

**Comment by rplotkin** [comment]
I am an idiot.

**Comment by ph3b** [comment]
It appears that you are not the only idiot running into this issue. Care to you share your solution? 😅

**Comment by acro5piano** [comment]
I am another idiot, so run into the same problem.

I fixed it by typing thunk middleware in the same way as example.
Did you setup thunk middleware correctly?

```ts
	// Declaring the type of the redux-thunk middleware is what makes
	// `store.dispatch` work. (redux@4.x, redux-thunk@2.3.x)
	const thunk: ThunkMiddleware<State, AnyAction> = thunkMiddleware;
	const store = createStore(reducer, applyMiddleware(thunk));
```
