### ISSUE TITLE
bindThunkAction uses incorrect typings for dispatch

### ISSUE THREAD

**Issue by jussikinnula** [xdave/typescript-fsa-redux-thunk#12]
This is for the old `typescript-fsa-redux-thunk` v1.0.1 (I did try already 2.0.0 beta.8, but the examples didn't work, and it might actually not be production ready yet).

Example code:
```
import actionCreatorFactory from 'typescript-fsa';
import { bindThunkAction } from 'typescript-fsa-redux-thunk';
const actionCreator = actionCreatorFactory();

export const fooAsync = actionCreator.async<string, number>('FOO');
export const foo = bindThunkAction(fooAsync, (param) => {
  return Promise.resolve(param.length);
});

export const barAsync = actionCreator.async<string, number>('BAR');
export const bar = bindThunkAction(barAsync, async (param, dispatch) => {
  const result = await dispatch(foo(param));
  // ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  return Promise.resolve(param.length);
});
```

Using `dispatch(foo(param)))` gives an error: `Type '{ async: AsyncActionCreators<any, any, Error>; action: ThunkActionCreator<any, Promise<any>, stri...' is not assignable to type 'ActionCreator<any>'.`

The workaround we're using at the moment is to define type for dispatch as plain `Function`.

I know that typescript-fsa-redux-thunk v2 should fix also the issue, but it would be nice to try to fix v1 also before getting v2 production ready.

**Comment by xdave** [comment]
Hmm can you explain what was wrong with the examples?

**Comment by xdave** [comment]
Also, for the v1 error, can you try specifying types for the state and the error?, ie:

`const fooAsync = actionCreator.async<State, string, number, Error>('FOO');`

**Comment by xdave** [comment]
@jussikinnula I'm probably not going to backport a fix for 1.x at this point.  I've updated the v2 branch (beta version) to support redux@4.x and redux-thunk@2.3.x.  Please see here for more details: https://github.com/xdave/typescript-fsa-redux-thunk/issues/11#issuecomment-393031497
