### ISSUE TITLE
custom asyncFactory<State> issue

### ISSUE THREAD

**Issue by septs** [xdave/typescript-fsa-redux-thunk#13]
**asyncFactory** method signature
https://github.com/xdave/typescript-fsa-redux-thunk/blob/1b50ed35cc4bd7a5e2046a7e9bfe302788c7b826/src/index.ts#L59-L65

Define asyncFactory generic
```typescript
const createAsync = asyncFactory<RootState>(create);
```

Error message

'createAsync' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer. ts(7022)

**Comment by septs** [comment]
@xdave

**Comment by xdave** [comment]
Hmm, I apologize for not noticing this issue until now.  I'm looking into it.

**Comment by xdave** [comment]
OK, I just ran a test to see if I could make this happen, and I couldn't except in a rare circumstance (if a thunk didn't return a value, and the return type was inferred).

Here's the version of everything related that I have installed:

```
    "@types/node": "^11.12.2",
    "@types/redux-thunk": "^2.1.0",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0",
    "ts-node": "^8.0.3",
    "tslib": "^1.9.3",
    "typescript": "^3.4.1",
    "typescript-fsa": "^3.0.0-beta-2",
    "typescript-fsa-reducers": "^1.2.0",
    "typescript-fsa-redux-thunk": "^2.0.0-beta.11"
```

Without seeing more of your code or more context of some kind, I can't think of how this might happen.

**Comment by xdave** [comment]
@septs

**Comment by xdave** [comment]
@septs 
I did come across this recently.  Turns out that if you pass your state type into asyncFactory, because your reducers depend on the type of your async actions, it creates a dependency cycle.

The break the cycle, pass a slightly different type into asyncFactory:

```ts
interface ActionState extends RootState {}
const createAsync = asyncFactory<ActionState>(create);
```

**Comment by xdave** [comment]
This will be fixed in typescript in 3.7 https://github.com/microsoft/TypeScript/pull/33050

**Comment by septs** [comment]
Upstream merged.

**Comment by xdave** [comment]
This still appears not to work. Determining options.

**Comment by septs** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9fc4c8ebb8425ca27a625c0dbe738ae19d406c43/types/react-redux/index.d.ts#L42-L49

```typescript
/**
 * This interface can be augmented by users to add default types for the root state when
 * using `react-redux`.
 * Use module augmentation to append your own type definition in a your_custom_type.d.ts file.
 * https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation
 */
// tslint:disable-next-line:no-empty-interface
export interface DefaultRootState {}
```

@xdave This is a preferable method

**Comment by septs** [comment]
```typescript
declare module 'typescript-fsa-redux-thunk' {
  interface DefaultRootState extends RootState {}
}
```

In this way, the problem is solved
