### ISSUE TITLE
Example for thunkToAction

### ISSUE THREAD

**Issue by agneshoving** [xdave/typescript-fsa-redux-thunk#15]
Hey,

Could you provide an example for the thunkToAction function? I'm upgrading from version 1.x to 2.x and I don't really get it. 

```
const authActionCreator = actionCreatorFactory(NAME);

const asyncAuthActionCreator = asyncFactory<State>(authActionCreator);

export const updateAuth = authActionCreator<any>("UPDATE_AUTH");
export const updateMe = authActionCreator<User>("UPDATE_ME");
export const updateVersion = authActionCreator<string>("UPDATE_VERSION");

export const purge = asyncAuthActionCreator<void, void>(
  'PURGE',
  async (params, dispatch) => {
    dispatch({type: PURGE, key: ROOT_KEY, result: () => null});
  }
);
export const purgeAction = thunkToAction(purge);
```

This is what i have now but i am getting an typescript error: 

`Error:(31, 42) TS2345: Argument of type '{ async: AsyncActionCreators<void, void, Error>; action: (params?: void | undefined) => ThunkAction<PromiseLike<void>, State, any, AnyAction>; }' is not assignable to parameter of type 'ThunkCreator<unknown, unknown, unknown>'.
  Type '{ async: AsyncActionCreators<void, void, Error>; action: (params?: void | undefined) => ThunkAction<PromiseLike<void>, State, any, AnyAction>; }' provides no match for the signature '(params?: unknown): ThunkAction<PromiseLike<unknown>, unknown, any, AnyAction>'.`

**Comment by agneshoving** [comment]
Ah i think i figured it out. You have to add it has to be

`
export const purgeAction = thunkToAction(purge.action);
`

**Comment by xdave** [comment]
I'm considering getting rid of thunkToAction. It was meant to fix the return type of thunk action creators that are bound to dispatch.

However, I have a new implementation of this library coming which is designed around react hooks, and the react hooks reducer implementation does not provide a return type for dispatch at all (last I checked).

The idea is to get new state using getState after your reducer handles it.
