### ISSUE TITLE
Dispatching without an argument

### ISSUE THREAD

**Issue by corydeppen** [xdave/typescript-fsa-redux-thunk#2]
From what I can tell, it's not possible to dispatch a thunk that doesn't accept an argument. I was hoping to create an action creator where I could specify the state, response, and error types, similar to the `ActionCreatorFactory` in typescript-fsa that returns an `EmptyActionCreator` when the payload type isn't specified. I'm still wrapping my head around the concepts, so I may be misunderstanding one or more pieces.

**Comment by xdave** [comment]
I wish I could make it do that.  The `.async()` method on the action creator factory has a bunch of overloaded generic type params, and typescript differentiates between which version is called based on the number of arguments.

So, if you give it three type params, it'll assume you want a regular ActionCreator that takes:
- params type,
- result type
- error type

So, what I do as a work-around is to provide the params type as `any` and just pass an empty object `{}` as the only parameter.

I may mess around with it tonight and see if there's a way around it.

**Comment by xdave** [comment]
Another flaw I'm thinking about fixing is that the Result type is always wrapped in a promise.  In other words, it always assumes you're going to return a promise from the thunk.

If I change that, I'll do a major version bump and document it.

**Comment by xdave** [comment]
@corydeppen This should work now.  I've published version 2.x beta.  Check the readme in the (now default) `v2` branch for more info.  Lots of changes.

**Comment by aleksey-shmatov** [comment]
Should dispatching without an argument work in 2.2 version? What should I specify as a type of params?

**Comment by xdave** [comment]
@aleksey-shmatov  Sorry for late response..... I *think* you just leave the argument in the function call out. and it should work. No need to change the type params.  If not, wait for my new beta coming soon (I'm waiting for an upstream bug to be fixed), in which it works for sure.  I'll keep you posted.

**Comment by xdave** [comment]
OK I've found a workaround for the `typescript-fsa` bug I was talking about, and I've published a new beta (2.0.0-beta.8).  Please check it out and let me know if you have any issues.  Dispatching without an argument should work fine.

**Comment by xdave** [comment]
This should work now
