### ISSUE TITLE
Bring back extra argument support

### ISSUE THREAD

**Issue by Filipeue** [xdave/typescript-fsa-redux-thunk#22]
Since May 2016 redux-thunk middleware supports extra argument. Main reason beeing to be able to mock external API calls in tests (https://github.com/reduxjs/redux-thunk/commit/41aefcc28a80d2b21f8ee1e68639757bf6d7ba49#diff-1fdf421c05c1140f6d71444ea2b27638). The implementation hasn't changed so far, so I see no reason why typescript-fsa-redux-thunk should not support that feature.

**Comment by xdave** [comment]
@Filipeue I agree. I will be addressing this.

**Comment by sv1809** [comment]
@xdave please have a look at https://github.com/xdave/typescript-fsa-redux-thunk/pull/23

**Comment by xdave** [comment]
@sv1809  works for me

**Comment by Filipeue** [comment]
@sv1809 great job man <3 , but I do not quite agree with your implementation.
In the original implementation you could pass extra argument in `asyncFactory` so every action you create with this factory has already automatically inserted ExtraArgument.
Have a look here (where ExtraArgument was removed) https://github.com/xdave/typescript-fsa-redux-thunk/commit/a5dd46b40c112ddaf2b0fa6d37cdacd968c34d1d. Thoughtout apps I contributed to, common usecase was to set ExtraArgument at app startup and never change it later. So it is not convenient to set ExtraArgument for every action separately.
Guess this would be sufficient:
```
export const asyncFactory = <S, EA = any>(
	create: ActionCreatorFactory,
	resolve: () => Promise<void> = Promise.resolve.bind(Promise),
) =>
	<P, R, E = any, A = EA>(
```

**Comment by xdave** [comment]
@Filipeue you are correct.  slight oversight on my part. I can fix @sv1809's implementation.

**Comment by xdave** [comment]
@Filipeue  see the tests in `src/issue-22.spec.ts` for usage. :)

**Comment by Filipeue** [comment]
thanks @xdave works as expected :)
