### ISSUE TITLE
Targeting ES6

### ISSUE THREAD

**Issue by jasonvasquez** [xdave/typescript-fsa-redux-thunk#3]
Is there any specific reason to target ES6  in `tsconfig.json`?  I'm attempting to integrate the library into my project, but my production builds use UglifyJS, and it's picking up the ES6-compiled JS, and failing.  (Or at least that's my working theory! :))

**Comment by xdave** [comment]
Two versions are shipped with this project.

One is ES6 in the `es` directory of the package, and the other (the ES5 version) is in `lib`.   The ES5 version is created using the `tsconfig.lib.json` project.

`npm run build:lib`... runs `tsc -p tsconfig.lib.json`.

**Comment by xdave** [comment]
Are you using webpack or something to pull the module into your build?

You could create an alias:
```ts
alias: {
    "typescript-fsa-redux-thunk": "typescript-fsa-redux-thunk/lib"
}
```

**Comment by xdave** [comment]
It's a double-edged sword with these bundlers.

- On the one hand, they want to pull in the ES5 version to do tree shaking using the static `import` syntax of es6 modules
    - and transform the imports to use require(),
- and then they refuse to compile the file to ES5 -- you have to enable that manually.

I'm not sure if webpack has another way other than using an alias.

**Comment by rluiten** [comment]
Thanks for this issue, i just ran into this myself testing in IE11 and Edge and I can deal with the alias work around thanks for posting it.

Before finding this thread, I tried pulling in your typescript as a local file and it was fine, this may be a naive idea but is there a way to include the original typescript in the shipped module, or is that not possible or produces other problems ?

So many parts of typescript are wonderful, but I sure seem to get a lot of paper cuts working with external code and the npm modules.

BTW lover your tiny module finding it very useful :).

**Comment by xdave** [comment]
@rluiten Typescript isn't really meant to be shipped, but I could include the `src` dir in the next release (whenever I get around to it).  That would mean you would:
```ts
import { bindThunkAction } from 'typescript-fsa-redux-thunk/src';

...
```

**Comment by rluiten** [comment]
I've seen a few libraries ship the typescript now, I havn't got enough experience with publishing via npm to have any strong opinions, just seems like a good idea to ship it given your clear explanation of the gotcha's around publishing.

Thanks for your great library.

**Comment by xdave** [comment]
I'll probably do that next release.  2.0 coming soon.

**Comment by xdave** [comment]
@rluiten @jasonvasquez 
I've made the ES5 build the default (in `lib/`), removed the `es` build, and shipped the typescript sources in `src/`.
