### ISSUE TITLE
Add support for more flexible promise type determination

### ISSUE THREAD

**Issue by namoscato** [xdave/typescript-fsa-redux-thunk#8]
I am trying to use this utility in an AngularJS 1.x project; however, the implementation of `isPromise()` is incompatible with AngularJS's [`$q` promise](https://docs.angularjs.org/api/ng/service/$q#the-promise-api). Thoughts on the best way to get around this?

**Comment by xdave** [comment]
@namoscato sorry I haven't got back to you, been extremely busy lately.

Essentially, `isPromise` just needs to check if the `thing` being passed to `isPromise` has a `then` and `catch` method on it instead of `instanceof Promise`.  A work around would be to convert your angular promise into a standard `Promise` before returning it from your thunk.  ie.:

```ts
    return Promise.resolve(angularPromise);
```

**Comment by namoscato** [comment]
@xdave, no worries; thanks for the reply!

Yeah, that could work. Unfortunately, Internet Explorer [does not implement `Promise`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Browser_compatibility), which I would need to support, but I guess I could look at incorporating a polyfill.

**Comment by xdave** [comment]
Ah, that's right.  Using a polyfill should work.  I do that automatically now without even thinking about it. heh.

**Comment by xdave** [comment]
I'll still consider changing it to just check for a more promise-like type.

**Comment by xdave** [comment]
@namoscato So, my latest refactorings (not pushed yet) are making me go back to the 1.x behavior -- in which you will not have to call `isPromise` as thunks will always return a promise.  I'm blocked by what I think might be a bug in the new `typescript-fsa` 3.0 beta.  I'll keep you posted.  In either case, you should use a `Promise` polyfill for browsers that do not support it, as I do invoke the `Promise` constructor in the new code (ie: `Promise.resolve(...)`).

**Comment by xdave** [comment]
@namoscato OK I've found a workaround for the `typescript-fsa` bug I was talking about, and I've published a new beta (2.0.0-beta.8).  Please check it out and let me know if you have any issues.

You won't have to check anything with `isPromise()` anymore, but you still need a working `Promise` constructor available in your environment, even if it ends up returning an angular promise.
